# Generated by Django 4.2.7 on 2024-06-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_nom_prenom', models.CharField(max_length=150)),
                ('dr_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Domaines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('', 'Role...'), ('PRESIDENT', 'PRESIDENT'), ('EXAMINATEUR', 'EXAMINATEUR'), ('RAPPORTEUR', 'RAPPORTEUR')], max_length=50)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses_ci.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Specialites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=105, verbose_name='Nom')),
                ('auteur_prenom', models.CharField(max_length=150)),
                ('auteur_email', models.EmailField(max_length=100)),
                ('theme', models.CharField(max_length=255, unique=True)),
                ('resume', models.TextField()),
                ('date_soutenance', models.DateField()),
                ('mot_cle', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='thesis_files/')),
                ('directeur', models.ManyToManyField(to='theses_ci.directeurs')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses_ci.domaines')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses_ci.institutions')),
                ('jury', models.ManyToManyField(to='theses_ci.membrejury')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses_ci.specialites')),
            ],
        ),
        migrations.AddField(
            model_name='directeurs',
            name='dr_universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses_ci.institutions'),
        ),
    ]
