# Generated by Django 5.0.4 on 2024-08-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses_ci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theses',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='theses/'),
        ),
    ]
